### ISSUE TITLE
Dead click when previewing trade

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#4500]
### Overview

When making a trade from USDC.AVA -> BCH.BCH clicking "preview trade" does nothing. 

### References and additional details

Error thrown to console:

```
{
    "error": {
        "message": "Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.",
        "stack": "Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.\n    at c.decodeParametersWith (https://juice.shapeshift.com/static/js/11.79ed7e98.js:725:241637)\n    at c.decodeParameters (https://juice.shapeshift.com/static/js/11.79ed7e98.js:725:241512)\n    at h._decodeMethodReturn (https://juice.shapeshift.com/static/js/11.79ed7e98.js:725:341986)\n    at c.outputFormatter (https://juice.shapeshift.com/static/js/11.79ed7e98.js:725:347796)\n    at c.formatOutput (https://juice.shapeshift.com/static/js/11.79ed7e98.js:725:211341)",
        "kind": "Error"
    },
    "message": "onSubmit error",
    "timestamp": "2023-05-15T05:52:11.882Z",
    "namespace": "App:TradeInput",
    "status": "error"
}
```

![image](https://github.com/shapeshift/web/assets/125113430/45654156-9daf-4134-af1c-2946fe77af01)

### Acceptance Criteria

Should be able to preview the trade above without dead click, or provide error state in UI to prevent invalid preview.

### Estimated effort

3 hours

**Comment by woodenfurniture** [comment]
While investigating, I noticed by pure chance that the bug was not reproducible when on #4492. Seems that this issue is actually related to token approvals and dead click for the trade pair reported here is actually due to an error thrown by web3:

```
Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at ABICoder.decodeParametersWith (index.js:304:1)
    at ABICoder.decodeParameters (index.js:291:1)
    at Contract._decodeMethodReturn (index.js:493:1)
    at Method.outputFormatter (index.js:800:1)
    at Method.formatOutput (index.js:148:1)
    at sendTxCallback (index.js:531:1)
    at eval (index.js:305:1)
    at request.onreadystatechange (index.js:98:1)
 ```

Anyway, this issue will be solved once #4492 is merged.
