### ISSUE TITLE
WETH input broken in swapper

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#5922]
### Overview

WETH of all flavors is broken as an input asset on the swapper

### References and additional details

1. select WETH on ETH (or another chain)
2. attempt to get a rate 
3. see we show the following console err
```
2apiState.ts:870 Error: missing sellAssetUsdRate
    at Object.queryFn (swappersApi.ts:53:38)
    at apiState.ts:804:65
    at apiState.ts:23:23
    at Object.next (apiState.ts:4:53)
    at apiState.ts:85:65
    at new Promise (<anonymous>)
    at S (apiState.ts:67:12)
    at f (apiState.ts:768:54)
    at index.ts:1237:61
    at index.ts:38:23
```

### Acceptance Criteria

- WETH works in the swapper as an input asset

**Comment by 0xean** [comment]
<img width="732" alt="Screenshot 2023-12-21 at 11 11 30 AM" src="https://github.com/shapeshift/web/assets/15096737/f086d82e-5343-441c-9d83-3817d6d79f6d">
