### ISSUE TITLE
Swapper flow fails for ETH <> BTC transaction 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#5945]
to repro:

1. connect an EVM wallet
2. Go to swapper and attempt to swap ETH to BTC with thorchain
3. enter a BTC addy
4. click next, no information is presented as seen in the below recording

https://github.com/shapeshift/web/assets/15096737/b6272aae-fb4c-4269-82cd-9f4e4fd864dd

This doesn't seem to affect basic EVM to EVM swaps, not sure what else is affected.

**Comment by 0xean** [comment]
Could be related to the BTC address entered as I see the following in the console

```
unstoppable-domains.ts:79 Error: invalid address (argument="address", value="bc1qcxjl4q3shzcyn0ywrvwzv94789hx56x3vvj3pt", code=INVALID_ARGUMENT, version=address/5.7.0) (argument="addr", value="bc1qcxjl4q3shzcyn0ywrvwzv94789hx56x3vvj3pt", code=INVALID_ARGUMENT, version=abi/5.7.0)
    at s.makeError (index.ts:224:23)
    at s.throwError (index.ts:233:20)
    at s.throwArgumentError (index.ts:236:21)
    at x._throwError (abstract-coder.ts:38:16)
    at x.encode (address.ts:17:18)
    at array.ts:57:19
    at Array.forEach (<anonymous>)
    at s (array.ts:43:12)
    at S.encode (tuple.ts:51:16)
    at C.encode (abi-coder.ts:86:15)
    ```
